---
- hosts: dev_ansible_server
  become: true

  tasks:
  - name: create docker image using war file
    command: docker build -t k8s-devops-image:latest .
    args:
      chdir: /opt/ansible_playbooks/warfile_k8s/

  - name: create tag to image
    command: docker tag k8s-devops-image verholyak/k8s-devops-image

  - name: push image on to dockerhub
    command: docker push verholyak/k8s-devops-image

  - name: remove docker images form ansible server
    command: docker rmi k8s-devops-image:latest verholyak/k8s-devops-image
